# See https://docs.aspect.build/workflows/configuration
workspaces:
  .:
    icon: esbuild
    label: rules_esbuild
  e2e/smoke:
    tasks: &skip-format-buildifier
      - format:
          without: true
      - buildifier:
          without: true
  e2e/smoke_rjs3:
    tasks: *skip-format-buildifier
  e2e/bundle:
    tasks: *skip-format-buildifier
  e2e/custom_version:
    tasks: *skip-format-buildifier
  e2e/npm-links:
    tasks: *skip-format-buildifier
  e2e/sourcemaps:
    tasks: *skip-format-buildifier
  e2e/toolchain_from_source:
    tasks: *skip-format-buildifier
  e2e/tsconfig:
    tasks: *skip-format-buildifier

tasks:
  - checkout:
      update_strategy: rebase
  - test:
      name: Bazel 7
      id: bazel-7
      bazel:
        flags: ['--test_tag_filters=-skip-on-bazel7']
      env:
        USE_BAZEL_VERSION: '7.x'
  - test:
      name: Bazel 8
      id: bazel-8
      bazel:
        flags: ['--test_tag_filters=-skip-on-bazel8']
      env:
        USE_BAZEL_VERSION: '8.x'
  - test:
      name: Bazel 9
      id: bazel-9
      bazel:
        flags: ['--test_tag_filters=-skip-on-bazel9']
      env:
        USE_BAZEL_VERSION: '9.x'
  - format:
      queue: aspect-medium
  - buildifier:
      queue: aspect-medium
  - finalization:
      queue: aspect-small
notifications:
  github: {}
