# See https://docs.aspect.build/workflows/configuration
workspaces:
  .:
    icon: esbuild
    label: rules_esbuild
  e2e/smoke:
    icon: bazel
    tasks:
      - format:
          without: true
      - buildifier:
          without: true
  e2e/bundle:
    icon: bazel
    tasks:
      - format:
          without: true
      - buildifier:
          without: true
  e2e/npm-links:
    icon: bazel
    tasks:
      - format:
          without: true
      - buildifier:
          without: true
  e2e/sourcemaps:
    icon: bazel
    tasks:
      - format:
          without: true
      - buildifier:
          without: true
  e2e/tsconfig:
    icon: bazel
    tasks:
      - format:
          without: true
      - buildifier:
          without: true

tasks:
  - checkout:
      update_strategy: rebase
  - buildifier:
      queue: aspect-small
  # NOTE: Bazel 6 ought to work, but is ending LTS end of 2025
  - test:
      name: 'Test (Bazel 7)'
      env:
        USE_BAZEL_VERSION: 7.x
      bazel:
        flags:
          - --test_tag_filters=-skip-on-bazel7
  - test:
      name: 'Test (Bazel 8)'
      env:
        USE_BAZEL_VERSION: 8.x
      bazel:
        flags:
          - --test_tag_filters=-skip-on-bazel8
  - finalization:
      queue: aspect-small
notifications:
  github: {}
