name: CI - Vanilla Bazel

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Note: linux is tested on Buildkite using Aspect Workflows
        os:
          - macos-latest
          # - windows-latest
        folder:
          - '.'
          - 'e2e/smoke'
          - 'e2e/custom_version'
          - 'e2e/npm-links'
          - 'e2e/path_mapping'
          - 'e2e/sourcemaps'
          - 'e2e/toolchain_from_source'
          - 'e2e/tsconfig'
          - 'e2e/bundle'

    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
      - run: bazel test //...
        working-directory: ${{ matrix.folder }}
        shell: bash
      - name: Optional ./test.sh
        working-directory: ${{ matrix.folder }}
        shell: bash
        run: |
          if [[ -f ./test.sh ]]; then
              ./test.sh
          else
              echo "No test.sh in ${PWD}; skipping"
          fi
