name: Mirror Releases
on:
  # Trigger manually in the UI
  workflow_dispatch:
  # Trigger daily at 06:55 UTC
  schedule:
    - cron: '55 6 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/mirror_releases.sh
          npx @bazel/buildifier esbuild/private/versions.bzl
          bazel run docs:update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: mirror external releases'
